create table if not exists public.student_diagnostic_records (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    diagnosis_type text default 'initial_mvp',
    vocab_band text,
    reading_profile text,
    grammar_gap text,
    writing_profile text,
    suggested_track text,
    module_scores jsonb default '{}'::jsonb,
    module_totals jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

alter table public.student_diagnostic_records disable row level security;

create index if not exists student_diagnostic_records_student_id_created_idx
on public.student_diagnostic_records (student_id, created_at desc);

create table if not exists public.student_profile_snapshots (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    source_record_id bigint references public.student_diagnostic_records(id) on delete set null,
    source_type text default 'initial_diagnosis',
    title_label text,
    stage_label text,
    growth_focus text,
    summary_text text,
    profile_payload jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

alter table public.student_profile_snapshots disable row level security;

create index if not exists student_profile_snapshots_student_id_created_idx
on public.student_profile_snapshots (student_id, created_at desc);

create table if not exists public.diagnostic_vocab_results (
    id bigint generated by default as identity primary key,
    diagnostic_id bigint not null unique references public.student_diagnostic_records(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    total_scored_items integer default 0,
    correct_count integer default 0,
    overall_accuracy double precision default 0,
    l1_accuracy double precision default 0,
    l2_accuracy double precision default 0,
    l3_accuracy double precision default 0,
    l4_accuracy double precision default 0,
    l5_accuracy double precision default 0,
    high_frequency_accuracy double precision default 0,
    reading_vocab_accuracy double precision default 0,
    polysemy_accuracy double precision default 0,
    confusable_accuracy double precision default 0,
    uncertain_rate double precision default 0,
    estimated_vocab_range text,
    vocab_level_label text,
    main_vocab_problem text,
    recommended_training_start text,
    self_check_json jsonb default '{}'::jsonb,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.diagnostic_vocab_results disable row level security;

create index if not exists diagnostic_vocab_results_student_id_created_idx
on public.diagnostic_vocab_results (student_id, created_at desc);

create table if not exists public.diagnostic_vocab_answers (
    id bigint generated by default as identity primary key,
    diagnostic_id bigint not null references public.student_diagnostic_records(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    item_id text not null references public.diagnostic_vocab_items(item_id) on delete restrict,
    selected_answer text,
    is_correct boolean default false,
    is_uncertain boolean default false,
    time_spent_seconds integer,
    question_type text,
    level text,
    diagnostic_tag text,
    created_at timestamptz default now()
);

alter table public.diagnostic_vocab_answers disable row level security;

create index if not exists diagnostic_vocab_answers_diagnostic_id_idx
on public.diagnostic_vocab_answers (diagnostic_id);

create index if not exists diagnostic_vocab_answers_student_id_created_idx
on public.diagnostic_vocab_answers (student_id, created_at desc);
