create table if not exists public.student_diagnostic_records (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    diagnosis_type text default 'initial_mvp',
    vocab_band text,
    reading_profile text,
    grammar_gap text,
    writing_profile text,
    suggested_track text,
    module_scores jsonb default '{}'::jsonb,
    module_totals jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

create index if not exists student_diagnostic_records_student_id_created_idx
on public.student_diagnostic_records (student_id, created_at desc);

create table if not exists public.student_profile_snapshots (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    source_record_id bigint references public.student_diagnostic_records(id) on delete set null,
    source_type text default 'initial_diagnosis',
    title_label text,
    stage_label text,
    growth_focus text,
    summary_text text,
    profile_payload jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

create index if not exists student_profile_snapshots_student_id_created_idx
on public.student_profile_snapshots (student_id, created_at desc);
