-- Run this once in the Supabase SQL Editor.

begin;

create table if not exists public.diagnostic_vocab_items (
    id bigint generated by default as identity primary key,
    item_id text not null,
    module text,
    level text,
    word text,
    primary_meaning_zh text,
    part_of_speech text,
    category text,
    sub_skill text,
    question_type text,
    question_text text,
    correct_answer text,
    wrong_option_1 text,
    wrong_option_2 text,
    wrong_option_3 text,
    explanation text,
    diagnostic_tag text,
    diagnostic_value text,
    difficulty_level text,
    grade_level text,
    frequency_band text,
    source_type text,
    source_note text,
    source_url_primary text,
    source_url_method text,
    is_anchor boolean default false,
    is_active boolean default true,
    version text,
    sentence text,
    notes_for_codex text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.diagnostic_vocab_items add column if not exists item_id text;
alter table public.diagnostic_vocab_items add column if not exists module text;
alter table public.diagnostic_vocab_items add column if not exists level text;
alter table public.diagnostic_vocab_items add column if not exists word text;
alter table public.diagnostic_vocab_items add column if not exists primary_meaning_zh text;
alter table public.diagnostic_vocab_items add column if not exists part_of_speech text;
alter table public.diagnostic_vocab_items add column if not exists category text;
alter table public.diagnostic_vocab_items add column if not exists sub_skill text;
alter table public.diagnostic_vocab_items add column if not exists question_type text;
alter table public.diagnostic_vocab_items add column if not exists question_text text;
alter table public.diagnostic_vocab_items add column if not exists correct_answer text;
alter table public.diagnostic_vocab_items add column if not exists wrong_option_1 text;
alter table public.diagnostic_vocab_items add column if not exists wrong_option_2 text;
alter table public.diagnostic_vocab_items add column if not exists wrong_option_3 text;
alter table public.diagnostic_vocab_items add column if not exists explanation text;
alter table public.diagnostic_vocab_items add column if not exists diagnostic_tag text;
alter table public.diagnostic_vocab_items add column if not exists diagnostic_value text;
alter table public.diagnostic_vocab_items add column if not exists difficulty_level text;
alter table public.diagnostic_vocab_items add column if not exists grade_level text;
alter table public.diagnostic_vocab_items add column if not exists frequency_band text;
alter table public.diagnostic_vocab_items add column if not exists source_type text;
alter table public.diagnostic_vocab_items add column if not exists source_note text;
alter table public.diagnostic_vocab_items add column if not exists source_url_primary text;
alter table public.diagnostic_vocab_items add column if not exists source_url_method text;
alter table public.diagnostic_vocab_items add column if not exists is_anchor boolean default false;
alter table public.diagnostic_vocab_items add column if not exists is_active boolean default true;
alter table public.diagnostic_vocab_items add column if not exists version text;
alter table public.diagnostic_vocab_items add column if not exists sentence text;
alter table public.diagnostic_vocab_items add column if not exists notes_for_codex text;
alter table public.diagnostic_vocab_items add column if not exists created_at timestamptz default now();
alter table public.diagnostic_vocab_items add column if not exists updated_at timestamptz default now();

create unique index if not exists diagnostic_vocab_items_item_id_key
on public.diagnostic_vocab_items (item_id);

commit;

notify pgrst, 'reload schema';
